name: Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create placeholder .env
        run: cp .env.example .env
      - run: docker compose config
      - run: docker compose build
